define({
    "images": [{
        "name": "zaklynacz_dosczu.jpg",
        "caption": "img-zaklynacz_dosczu-capt",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Малярство",
        "categoryCode": "img-cat-malyarstvo",
    }, {
        "name": "zahubleni_tini.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Малярство",
        "categoryCode": "img-cat-malyarstvo"
    }, {
        "name": "wiz.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Малярство",
        "categoryCode": "img-cat-malyarstvo"
    }, {
        "name": "voskresinnja.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Малярство",
        "categoryCode": "img-cat-malyarstvo"
    }, {
        "name": "vesilla_v_kani_halylejskij.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Малярство",
        "categoryCode": "img-cat-malyarstvo"
    }, {
        "name": "velykyj_rahivnyk.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Абстракції",
        "categoryCode": "img-cat-abstraction"
    }, {
        "name": "spas.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Абстракції",
        "categoryCode": "img-cat-abstraction"
    }, {
        "name": "sonata.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Абстракції",
        "categoryCode": "img-cat-abstraction"
    }, {
        "name": "sad_angelskyh_pisen.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Абстракції",
        "categoryCode": "img-cat-abstraction"
    }, {
        "name": "rytual-600x652.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Абстракції",
        "categoryCode": "img-cat-abstraction"
    }, {
        "name": "rytual.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Абстракції",
        "categoryCode": "img-cat-abstraction"
    }, {
        "name": "rydannja.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Пейзаж",
        "categoryCode": "img-cat-landscape"
    }, {
        "name": "ryba_po.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Пейзаж",
        "categoryCode": "img-cat-landscape"
    }, {
        "name": "ryba.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Пейзаж",
        "categoryCode": "img-cat-landscape"
    }, {
        "name": "rozpjattja.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Пейзаж",
        "categoryCode": "img-cat-landscape"
    }, {
        "name": "rozmova.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Пейзаж",
        "categoryCode": "img-cat-landscape"
    }, {
        "name": "roman.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Пейзаж",
        "categoryCode": "img-cat-landscape"
    }, {
        "name": "provody_stomlenoho_soncja.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Пейзаж",
        "categoryCode": "img-cat-landscape"
    }, {
        "name": "pokynute_derevo.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ілюстрація",
        "categoryCode": "img-cat-illustration"
    }, {
        "name": "pereviznyk.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ілюстрація",
        "categoryCode": "img-cat-illustration"
    }, {
        "name": "pavel.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ілюстрація",
        "categoryCode": "img-cat-illustration"
    }, {
        "name": "pastuh.JPG",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ілюстрація",
        "categoryCode": "img-cat-illustration"
    }, {
        "name": "oczikuvannja_povnogo_misjacja.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ілюстрація",
        "categoryCode": "img-cat-illustration"
    }, {
        "name": "oboz.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ілюстрація",
        "categoryCode": "img-cat-illustration"
    }, {
        "name": "noj.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ілюстрація",
        "categoryCode": "img-cat-illustration"
    }, {
        "name": "nikolae.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "Narcissus.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "mistok.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "mawky.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "masky.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "mamaj2.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "mamaj.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "logo.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "lihtarnyk.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "kulbabyni_dity.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "kovczeg.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "kosar.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "koropy.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "korabel-mrij.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "konstantinos.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "iosafat.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "IMG_1199.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "ikar.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "hwylja.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "garderobe.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "ewoljucija.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "dvoje.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "czornogora.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "bohorodyca04.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "bohorodyca03.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "bohorodyca02.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "bohorodyca01.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "bohorodyca.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "apostoly.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "andriy_pervozvannyy.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }, {
        "name": "1z12.jpg",
        "caption": "img-caption-test",
        "size": "img-200x200",
        "material": "img-material-levkas",
        "category": "Ікона",
        "categoryCode": "img-cat-icon"
    }]
});